name: repository_at_start_of_controller
description: Repository at start of controller

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  analyzer: ^4.2.0
  custom_lint_builder: ^0.0.9+1
  source_gen: ^1.2.2
